//this source code was auto-generated by tolua#, do not modify it
using System;
using LuaInterface;

public class TimeManagerWrap
{
	public static void Register(LuaState L)
	{
		L.BeginClass(typeof(TimeManager), typeof(System.Object));
		L.RegFunction("SetInstance", SetInstance);
		L.RegFunction("Add", Add);
		L.RegFunction("New", _CreateTimeManager);
		L.RegFunction("__tostring", ToLua.op_ToString);
		L.RegVar("Instance", get_Instance, null);
		L.EndClass();
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int _CreateTimeManager(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 0)
			{
				TimeManager obj = new TimeManager();
				ToLua.PushObject(L, obj);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to ctor method: TimeManager.New");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int SetInstance(IntPtr L)
	{
		try
		{
			ToLua.CheckArgsCount(L, 1);
			TimeManager arg0 = (TimeManager)ToLua.CheckObject<TimeManager>(L, 1);
			TimeManager.SetInstance(arg0);
			return 0;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int Add(IntPtr L)
	{
		try
		{
			int count = LuaDLL.lua_gettop(L);

			if (count == 4)
			{
				TimeManager obj = (TimeManager)ToLua.CheckObject<TimeManager>(L, 1);
				System.Action arg0 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				int o = obj.Add(arg0, arg1, arg2);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else if (count == 5)
			{
				TimeManager obj = (TimeManager)ToLua.CheckObject<TimeManager>(L, 1);
				System.Action arg0 = (System.Action)ToLua.CheckDelegate<System.Action>(L, 2);
				LuaFunction arg1 = ToLua.CheckLuaFunction(L, 3);
				float arg2 = (float)LuaDLL.luaL_checknumber(L, 4);
				int arg3 = (int)LuaDLL.luaL_checknumber(L, 5);
				int o = obj.Add(arg0, arg1, arg2, arg3);
				LuaDLL.lua_pushinteger(L, o);
				return 1;
			}
			else
			{
				return LuaDLL.luaL_throw(L, "invalid arguments to method: TimeManager.Add");
			}
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}

	[MonoPInvokeCallbackAttribute(typeof(LuaCSFunction))]
	static int get_Instance(IntPtr L)
	{
		try
		{
			ToLua.PushObject(L, TimeManager.Instance);
			return 1;
		}
		catch (Exception e)
		{
			return LuaDLL.toluaL_exception(L, e);
		}
	}
}

