//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protoLoginUser.proto
// Note: requires additional types generated from: protoBase.proto
namespace protoLoginUser
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CS_LoginUser")]
  public partial class CS_LoginUser : global::ProtoBuf.IExtensible
  {
    public CS_LoginUser() {}
    
    private string _uid = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"uid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string uid
    {
      get { return _uid; }
      set { _uid = value; }
    }
    private string _userName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"userName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string userName
    {
      get { return _userName; }
      set { _userName = value; }
    }
    private string _passWord = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"passWord", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string passWord
    {
      get { return _passWord; }
      set { _passWord = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SC_LoginUser")]
  public partial class SC_LoginUser : global::ProtoBuf.IExtensible
  {
    public SC_LoginUser() {}
    
    private int _Ret = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"Ret", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int Ret
    {
      get { return _Ret; }
      set { _Ret = value; }
    }
    private uint _Sex = default(uint);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"Sex", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Sex
    {
      get { return _Sex; }
      set { _Sex = value; }
    }
    private string _Nick = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"Nick", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Nick
    {
      get { return _Nick; }
      set { _Nick = value; }
    }
    private uint _Uid = default(uint);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"Uid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(uint))]
    public uint Uid
    {
      get { return _Uid; }
      set { _Uid = value; }
    }
    private string _Token = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"Token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Token
    {
      get { return _Token; }
      set { _Token = value; }
    }
    private protoBase.GVector3 _vet = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"vet", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public protoBase.GVector3 vet
    {
      get { return _vet; }
      set { _vet = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}