---@class Tween : ABSSequentiable
---@field public timeScale Single
---@field public isBackwards bool
---@field public id Object
---@field public target Object
---@field public easeOvershootOrAmplitude Single
---@field public easePeriod Single
---@field public fullPosition Single
local Tween = {}
