---@class ScreenOrientation : Enum
---@field public value__ Int32
---@field public Unknown number
---@field public Portrait number
---@field public PortraitUpsideDown number
---@field public LandscapeLeft number
---@field public LandscapeRight number
---@field public AutoRotation number
---@field public Landscape number
local ScreenOrientation = {}
